apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-stage-private
  namespace: default
spec:
  secretName: ssl-cert-stage-private
  issuerRef:
    name: letsencrypt-stage
    kind: ClusterIssuer
  commonName: graf.zefirnikolov.org
  dnsNames:
  - graf.zefirnikolov.org
