apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ssl-cert-prod
  namespace: default
spec:
  secretName: ssl-cert-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: www.zefirnikolov.org
  dnsNames:
  - www.zefirnikolov.org
