apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-stage
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: zefirnikolov@gmail.com # Replace with your email address
    privateKeySecretRef:
      name: letsencrypt-stage
    solvers:
    - http01:
        ingress:
          class: nginx
      selector: {}
