apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: public-routing
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - www.zefirnikolov.org
    - zefirnikolov.org
    secretName: ssl-cert-prod
  rules:
  - host: zefirnikolov.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web
            port:
              number: 80
  - host: www.zefirnikolov.org
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: web
            port:
              number: 80
